<?php
$page_security='SA_HRM_MANAGE_BENEFITS';$path_to_root='../..';include($path_to_root.'/includes/session.inc');include_once($path_to_root.'/includes/ui.inc');include_once($path_to_root.'/hrm/includes/db/hrm_ben_001_plan_db.inc');page(_('Optional Benefits Governance'));
$a=isset($_POST['ben_action'])?(string)$_POST['ben_action']:'';
if($a!==''&&!check_csrf_token())display_error(_('Invalid CSRF token.'));
elseif($a==='plan'){$e=null;$r=hrm_ben_001_create_plan((int)$_POST['legal_entity_id'],trim((string)$_POST['plan_code']),$e);$r===false?display_error(_('Plan rejected: ').$e):display_notification(_('Plan identity created: ').$r['plan_id']);}
elseif($a==='version'){$e=null;$r=hrm_ben_001_append_plan_version(array('plan_id'=>(int)$_POST['plan_id'],'version_token'=>trim((string)$_POST['version_token']),'effective_from'=>is_date($_POST['effective_from'])?date2sql($_POST['effective_from']):'','effective_to'=>empty($_POST['effective_to'])?null:(is_date($_POST['effective_to'])?date2sql($_POST['effective_to']):'invalid'),'status_token'=>(string)$_POST['status_token'],'coverage_basis_code'=>trim((string)$_POST['coverage_basis_code']),'contribution_basis_code'=>trim((string)$_POST['contribution_basis_code']),'pack_adapter_version_id'=>empty($_POST['pack_adapter_version_id'])?null:(int)$_POST['pack_adapter_version_id'],'provider_adapter_version_id'=>empty($_POST['provider_adapter_version_id'])?null:(int)$_POST['provider_adapter_version_id'],'source_evidence_sha256'=>trim((string)$_POST['source_evidence_sha256']),'predecessor_plan_version_id'=>empty($_POST['predecessor_plan_version_id'])?null:(int)$_POST['predecessor_plan_version_id']),$e);$r===false?display_error(_('Plan version rejected: ').$e):display_notification(_('Immutable plan version created: ').$r['version_sha256']);}
elseif($a==='eligibility'){$e=null;$r=hrm_ben_001_append_eligibility_version(array('plan_version_id'=>(int)$_POST['plan_version_id'],'effective_from'=>is_date($_POST['effective_from'])?date2sql($_POST['effective_from']):'','effective_to'=>empty($_POST['effective_to'])?null:(is_date($_POST['effective_to'])?date2sql($_POST['effective_to']):'invalid'),'resolver_code'=>'scope_match_v1','rule_payload_json'=>(string)$_POST['rule_payload_json'],'rule_artifact_sha256'=>trim((string)$_POST['rule_artifact_sha256']),'predecessor_eligibility_version_id'=>empty($_POST['predecessor_eligibility_version_id'])?null:(int)$_POST['predecessor_eligibility_version_id']),$e);$r===false?display_error(_('Eligibility version rejected: ').$e):display_notification(_('Eligibility version created: ').$r['eligibility_sha256']);}
elseif($a==='window'){$e=null;$r=hrm_ben_001_append_window(array('plan_version_id'=>(int)$_POST['plan_version_id'],'window_code'=>trim((string)$_POST['window_code']),'window_start'=>is_date($_POST['window_start'])?date2sql($_POST['window_start']):'','window_end'=>is_date($_POST['window_end'])?date2sql($_POST['window_end']):'','qualifying_basis_code'=>trim((string)$_POST['qualifying_basis_code']),'evidence_sha256'=>trim((string)$_POST['evidence_sha256']),'predecessor_window_id'=>empty($_POST['predecessor_window_id'])?null:(int)$_POST['predecessor_window_id']),$e);$r===false?display_error(_('Enrollment window rejected: ').$e):display_notification(_('Enrollment window created: ').$r['window_sha256']);}
start_form();hidden('_token',ensure_csrf_token());hidden('ben_action','plan');start_table(TABLESTYLE2);text_row_ex(_('Legal Entity ID:'),'legal_entity_id',12,12);text_row_ex(_('Plan Code:'),'plan_code',36,64);end_table(1);submit_center('plan_submit',_('Create Plan Identity'));end_form();
start_form();hidden('_token',ensure_csrf_token());hidden('ben_action','version');start_table(TABLESTYLE2);text_row_ex(_('Plan ID:'),'plan_id',12,12);text_row_ex(_('Version Token:'),'version_token',36,64);date_row(_('Effective From:'),'effective_from');date_row(_('Effective To:'),'effective_to');array_selector_row(_('Status:'),'status_token','active',array('draft'=>_('Draft'),'active'=>_('Active'),'closed'=>_('Closed')));text_row_ex(_('Coverage Basis Code:'),'coverage_basis_code',36,64);text_row_ex(_('Contribution Basis Code:'),'contribution_basis_code',36,64);text_row_ex(_('Pack Adapter Version ID:'),'pack_adapter_version_id',12,12);text_row_ex(_('Provider Adapter Version ID:'),'provider_adapter_version_id',12,12);text_row_ex(_('Predecessor Plan Version ID:'),'predecessor_plan_version_id',12,12);text_row_ex(_('Source Evidence SHA-256:'),'source_evidence_sha256',68,64);end_table(1);submit_center('version_submit',_('Append Plan Version'));end_form();
start_form();hidden('_token',ensure_csrf_token());hidden('ben_action','eligibility');start_table(TABLESTYLE2);text_row_ex(_('Plan Version ID:'),'plan_version_id',12,12);date_row(_('Effective From:'),'effective_from');date_row(_('Effective To:'),'effective_to');textarea_row(_('Scope-match Rule JSON:'),'rule_payload_json',null,60,5);text_row_ex(_('Rule Artifact SHA-256:'),'rule_artifact_sha256',68,64);text_row_ex(_('Predecessor Eligibility Version ID:'),'predecessor_eligibility_version_id',12,12);end_table(1);submit_center('eligibility_submit',_('Append Eligibility Version'));end_form();
start_form();hidden('_token',ensure_csrf_token());hidden('ben_action','window');start_table(TABLESTYLE2);text_row_ex(_('Plan Version ID:'),'plan_version_id',12,12);text_row_ex(_('Window Code:'),'window_code',36,64);date_row(_('Window Start:'),'window_start');date_row(_('Window End:'),'window_end');text_row_ex(_('Qualifying Basis Code:'),'qualifying_basis_code',36,64);text_row_ex(_('Evidence SHA-256:'),'evidence_sha256',68,64);text_row_ex(_('Predecessor Window ID:'),'predecessor_window_id',12,12);end_table(1);submit_center('window_submit',_('Append Enrollment Window'));end_form();
display_note(_('BEN core is provider-neutral and country-neutral. No benefit types, rates, statutory schemes or national eligibility rules are created by this route.'));end_page();
?>