<?php
/** HRM-CMP-001 immutable range, review-cycle and budget administration. */
$page_security='SA_HRM_MANAGE_COMPENSATION';$path_to_root='../..';include($path_to_root.'/includes/session.inc');include_once($path_to_root.'/includes/ui.inc');include_once($path_to_root.'/hrm/includes/db/hrm_cmp_001_governance_db.inc');
page(_('Compensation Governance'));$action=isset($_POST['cmp_action'])?(string)$_POST['cmp_action']:'';
if($action!==''&&!check_csrf_token())display_error(_('Invalid CSRF token.'));
elseif($action==='range'){$entity=(int)$_POST['legal_entity_id'];$code=trim((string)$_POST['range_code']);$pred=null;$q=db_query('SELECT range_version_id FROM '.TB_PREF.'hrm_comp_salary_ranges WHERE legal_entity_id='.$entity.' AND range_code='.db_escape($code).' ORDER BY effective_from DESC,range_version_id DESC LIMIT 1');if($q&&db_num_rows($q)===1){$r=db_fetch_assoc($q);$pred=(int)$r['range_version_id'];}$x=array('legal_entity_id'=>$entity,'grade_id'=>(int)$_POST['grade_id'],'range_code'=>$code,'version_token'=>trim((string)$_POST['version_token']),'effective_from'=>is_date($_POST['effective_from'])?date2sql($_POST['effective_from']):'','effective_to'=>empty($_POST['effective_to'])?null:(is_date($_POST['effective_to'])?date2sql($_POST['effective_to']):'invalid'),'currency_code'=>trim((string)$_POST['currency_code']),'pay_basis'=>trim((string)$_POST['pay_basis']),'minimum_amount'=>trim((string)$_POST['minimum_amount']),'midpoint_amount'=>trim((string)$_POST['midpoint_amount']),'maximum_amount'=>trim((string)$_POST['maximum_amount']),'source_kind'=>(string)$_POST['source_kind'],'source_ref'=>trim((string)$_POST['source_ref']),'source_evidence_sha256'=>trim((string)$_POST['evidence_sha256']),'predecessor_range_version_id'=>$pred);$e=null;$r=hrm_cmp_001_create_salary_range($x,$e);$r===false?display_error(_('Range rejected: ').$e):display_notification(_('Immutable range created: ').$r['range_sha256']);}
elseif($action==='cycle'){$entity=(int)$_POST['legal_entity_id'];$code=trim((string)$_POST['cycle_code']);$pred=null;$q=db_query('SELECT review_cycle_id FROM '.TB_PREF.'hrm_comp_review_cycles WHERE legal_entity_id='.$entity.' AND cycle_code='.db_escape($code).' ORDER BY review_cycle_id DESC LIMIT 1');if($q&&db_num_rows($q)===1){$z=db_fetch_assoc($q);$pred=(int)$z['review_cycle_id'];}$x=array('legal_entity_id'=>$entity,'cycle_code'=>$code,'version_token'=>trim((string)$_POST['version_token']),'open_date'=>is_date($_POST['open_date'])?date2sql($_POST['open_date']):'','close_date'=>is_date($_POST['close_date'])?date2sql($_POST['close_date']):'','award_effective_from'=>is_date($_POST['award_effective_from'])?date2sql($_POST['award_effective_from']):'','award_effective_to'=>is_date($_POST['award_effective_to'])?date2sql($_POST['award_effective_to']):'','status_token'=>(string)$_POST['status_token'],'purpose_code'=>trim((string)$_POST['purpose_code']),'evidence_sha256'=>trim((string)$_POST['evidence_sha256']),'predecessor_review_cycle_id'=>$pred);$e=null;$r=hrm_cmp_001_create_review_cycle($x,$e);$r===false?display_error(_('Cycle rejected: ').$e):display_notification(_('Immutable review cycle created: ').$r['cycle_sha256']);}
elseif($action==='budget'){$cycle=(int)$_POST['review_cycle_id'];$currency=strtoupper(trim((string)$_POST['currency_code']));$pred=null;$q=db_query('SELECT budget_version_id FROM '.TB_PREF.'hrm_comp_budgets WHERE review_cycle_id='.$cycle.' AND currency_code='.db_escape($currency).' ORDER BY budget_version_id DESC LIMIT 1');if($q&&db_num_rows($q)===1){$z=db_fetch_assoc($q);$pred=(int)$z['budget_version_id'];}$e=null;$r=hrm_cmp_001_create_budget(array('review_cycle_id'=>$cycle,'currency_code'=>$currency,'budget_amount'=>trim((string)$_POST['budget_amount']),'evidence_sha256'=>trim((string)$_POST['evidence_sha256']),'predecessor_budget_version_id'=>$pred),$e);$r===false?display_error(_('Budget rejected: ').$e):display_notification(_('Immutable budget created: ').$r['budget_sha256']);}
start_form();hidden('_token',ensure_csrf_token());start_table(TABLESTYLE2);hidden('cmp_action','range');text_row_ex(_('Legal Entity ID:'),'legal_entity_id',12,12);text_row_ex(_('Grade ID:'),'grade_id',12,12);text_row_ex(_('Range Code:'),'range_code',24,64);text_row_ex(_('Version Token:'),'version_token',24,64);date_row(_('Effective From:'),'effective_from');date_row(_('Effective To:'),'effective_to');text_row_ex(_('Currency:'),'currency_code',5,3);text_row_ex(_('Pay Basis:'),'pay_basis',20,24);text_row_ex(_('Minimum:'),'minimum_amount',20,24);text_row_ex(_('Midpoint:'),'midpoint_amount',20,24);text_row_ex(_('Maximum:'),'maximum_amount',20,24);array_selector_row(_('Source:'),'source_kind','employer',array('employer'=>_('Employer'),'collective'=>_('Collective'),'legacy_review'=>_('Legacy Review'),'governed_correction'=>_('Governed Correction')));text_row_ex(_('Source Reference:'),'source_ref',40,160);text_row_ex(_('Evidence SHA-256:'),'evidence_sha256',68,64);end_table(1);submit_center('create_range',_('Create Range'));end_form();
start_form();hidden('_token',ensure_csrf_token());start_table(TABLESTYLE2);hidden('cmp_action','cycle');text_row_ex(_('Legal Entity ID:'),'legal_entity_id',12,12);text_row_ex(_('Cycle Code:'),'cycle_code',24,64);text_row_ex(_('Version Token:'),'version_token',24,64);date_row(_('Open Date:'),'open_date');date_row(_('Close Date:'),'close_date');date_row(_('Award Effective From:'),'award_effective_from');date_row(_('Award Effective To:'),'award_effective_to');array_selector_row(_('Status:'),'status_token','open',array('planned'=>_('Planned'),'open'=>_('Open'),'closed'=>_('Closed')));text_row_ex(_('Purpose Code:'),'purpose_code',30,64);text_row_ex(_('Evidence SHA-256:'),'evidence_sha256',68,64);end_table(1);submit_center('create_cycle',_('Create Review Cycle'));end_form();
start_form();hidden('_token',ensure_csrf_token());start_table(TABLESTYLE2);hidden('cmp_action','budget');text_row_ex(_('Review Cycle ID:'),'review_cycle_id',12,12);text_row_ex(_('Currency:'),'currency_code',5,3);text_row_ex(_('Budget Amount:'),'budget_amount',20,24);text_row_ex(_('Evidence SHA-256:'),'evidence_sha256',68,64);end_table(1);submit_center('create_budget',_('Create Budget Version'));end_form();display_note(_('CMP-001 stores immutable effective-dated configuration. No statutory rates, currency conversions or country defaults are inferred.'));end_page();
?>
