<?php
/** HRM-TAL-001 restricted confidential-case browser. */
$page_security='SA_HRSETTINGS';$path_to_root='../..';
include($path_to_root.'/includes/session.inc');
include_once($path_to_root.'/includes/ui.inc');
include_once($path_to_root.'/hrm/includes/db/hrm_tal_001_confidential_case_db.inc');
page(_('Confidential HR Cases'));
if(!function_exists('get_company_pref')||!hrm_tal_001_confidential_case_browser_allowed_for_database_version((string)get_company_pref('version_id',true))){display_error(_('Confidential-case browser access is not enabled until database version 1.0.979.'));end_page();exit;}
function htal1_cc_ui($k){return isset($_POST[$k])?trim((string)$_POST[$k]):'';}
function htal1_cc_notice($label,$result,$key){$suffix=!empty($result['idempotent'])?_(' (idempotent replay)'):'';display_notification($label.' '.(int)$result[$key].$suffix);}
$case=false;$action=isset($_POST['cc_action'])?(string)$_POST['cc_action']:'';
if($action!==''&&!check_csrf_token())display_error(_('Invalid CSRF token.'));
elseif($action==='open'){$error=null;$r=hrm_tal_001_open_confidential_case(array('subject_employee_id'=>htal1_cc_ui('subject_employee_id'),'case_type_code'=>htal1_cc_ui('case_type_code'),'purpose_code'=>htal1_cc_ui('purpose_code'),'opened_on'=>htal1_cc_ui('opened_on'),'retention_until'=>htal1_cc_ui('retention_until'),'sensitivity_code'=>htal1_cc_ui('sensitivity_code'),'title_reference_sha256'=>htal1_cc_ui('title_reference_sha256'),'case_reference_sha256'=>htal1_cc_ui('case_reference_sha256')),$error);if($r===false)display_error(_('Confidential case rejected: ').$error);else htal1_cc_notice(_('Confidential case recorded with immutable ID'),$r,'confidential_case_id');}
elseif($action==='grant'){$error=null;$r=hrm_tal_001_grant_confidential_case_access(array('confidential_case_id'=>htal1_cc_ui('grant_case_id'),'grantee_user_id'=>htal1_cc_ui('grantee_user_id'),'access_role_code'=>htal1_cc_ui('access_role_code'),'purpose_code'=>htal1_cc_ui('grant_purpose_code'),'valid_from'=>htal1_cc_ui('grant_valid_from'),'valid_to'=>htal1_cc_ui('grant_valid_to'),'grant_reference_sha256'=>htal1_cc_ui('grant_reference_sha256')),$error);if($r===false)display_error(_('Access grant rejected: ').$error);else htal1_cc_notice(_('Access evidence recorded with immutable ID'),$r,'confidential_case_access_grant_id');}
elseif($action==='revoke'){$error=null;$r=hrm_tal_001_revoke_confidential_case_access(array('confidential_case_id'=>htal1_cc_ui('revoke_case_id'),'grantee_user_id'=>htal1_cc_ui('revoke_grantee_user_id'),'effective_on'=>htal1_cc_ui('revoke_effective_on'),'revocation_reference_sha256'=>htal1_cc_ui('revocation_reference_sha256')),$error);if($r===false)display_error(_('Access revocation rejected: ').$error);else htal1_cc_notice(_('Access revocation evidence recorded with immutable ID'),$r,'confidential_case_access_grant_id');}
elseif($action==='read'){$error=null;$case=hrm_tal_001_read_confidential_case(htal1_cc_ui('read_case_id'),$error);if($case===false)display_error(_('Confidential case read rejected: ').$error);}
display_note(_('This surface is restricted to SA_HRSETTINGS and one exact confidential-case object at a time. It stores hash-only title/reference evidence, requires explicit purpose and retention, grants no automatic manager access, provides no case search/list/export, and has no payroll, compensation, accounting or employment-decision authority.'),0,1);
start_form();hidden('_token',ensure_csrf_token());hidden('cc_action','open');start_table(TABLESTYLE2);table_section_title(_('Open minimized confidential case'));text_row_ex(_('Subject Employee ID:'),'subject_employee_id',24,20);text_row_ex(_('Case type (employee_relations / grievance / investigation / accommodation / ethics / other_restricted):'),'case_type_code',32,32);text_row_ex(_('Purpose (case_management / investigation / employee_relations / legal_hold):'),'purpose_code',32,48);text_row_ex(_('Opened on (YYYY-MM-DD):'),'opened_on',16,10);text_row_ex(_('Retention until (YYYY-MM-DD):'),'retention_until',16,10);text_row_ex(_('Sensitivity (restricted / highly_restricted):'),'sensitivity_code',24,24);text_row_ex(_('Title/reference SHA-256 (raw title is not accepted):'),'title_reference_sha256',68,64);text_row_ex(_('Case reference SHA-256:'),'case_reference_sha256',68,64);end_table(1);submit_center('open_confidential_case',_('Record Confidential Case'));end_form();
start_form();hidden('_token',ensure_csrf_token());hidden('cc_action','grant');start_table(TABLESTYLE2);table_section_title(_('Grant explicit case-object access'));text_row_ex(_('Confidential Case ID:'),'grant_case_id',12,20);text_row_ex(_('Grantee User ID:'),'grantee_user_id',12,20);text_row_ex(_('Role (case_owner / case_reviewer / case_reader):'),'access_role_code',28,24);text_row_ex(_('Purpose (must match case):'),'grant_purpose_code',32,48);text_row_ex(_('Valid from (YYYY-MM-DD):'),'grant_valid_from',16,10);text_row_ex(_('Valid to (optional YYYY-MM-DD):'),'grant_valid_to',16,10);text_row_ex(_('Grant reference SHA-256:'),'grant_reference_sha256',68,64);end_table(1);submit_center('grant_confidential_case_access',_('Record Explicit Access'));end_form();
start_form();hidden('_token',ensure_csrf_token());hidden('cc_action','revoke');start_table(TABLESTYLE2);table_section_title(_('Append access revocation'));text_row_ex(_('Confidential Case ID:'),'revoke_case_id',12,20);text_row_ex(_('Grantee User ID:'),'revoke_grantee_user_id',12,20);text_row_ex(_('Effective on (YYYY-MM-DD):'),'revoke_effective_on',16,10);text_row_ex(_('Revocation reference SHA-256:'),'revocation_reference_sha256',68,64);end_table(1);submit_center('revoke_confidential_case_access',_('Record Access Revocation'));end_form();
start_form();hidden('_token',ensure_csrf_token());hidden('cc_action','read');start_table(TABLESTYLE2);table_section_title(_('Read one explicitly granted case object'));text_row_ex(_('Exact Confidential Case ID:'),'read_case_id',12,20);end_table(1);submit_center('read_confidential_case',_('View Granted Case'));end_form();
if(is_array($case)){start_table(TABLESTYLE);$labels=array('confidential_case_id'=>_('Case ID'),'subject_employee_id'=>_('Subject Employee ID'),'case_type_code'=>_('Case Type'),'purpose_code'=>_('Purpose'),'opened_on'=>_('Opened On'),'retention_until'=>_('Retention Until'),'sensitivity_code'=>_('Sensitivity'),'access_role_code'=>_('Current Access Role'));foreach($labels as $k=>$label)label_row($label,htmlspecialchars((string)$case[$k],ENT_QUOTES,'UTF-8'));end_table(1);}
end_page();
?>
