<?php
/** HRM-ESS-001 distinct executor/application route for approved bounded self-profile requests. */
$ess_apply_raw_method=isset($_SERVER['REQUEST_METHOD'])?(string)$_SERVER['REQUEST_METHOD']:'';$ess_apply_raw_query=isset($_SERVER['QUERY_STRING'])?(string)$_SERVER['QUERY_STRING']:'';$ess_apply_script=isset($_SERVER['SCRIPT_NAME'])?(string)$_SERVER['SCRIPT_NAME']:'';
$page_security='SA_HRM_EXECUTE_ESS_SELF_PROFILE_CHANGE';$path_to_root='../..';include_once($path_to_root.'/includes/session.inc');include_once($path_to_root.'/includes/ui.inc');
include_once($path_to_root.'/hrm/includes/db/ess_self_change_executor_db.inc');include_once($path_to_root.'/includes/hrm_ess_self_change_route.inc');include_once($path_to_root.'/includes/hrm_ess_self_change_review_route.inc');
hrm_ess_self_change_route_security_headers();$now=time();$company=function_exists('user_company')?(int)user_company():-1;$suffix='/hrm/ess/self_profile_change_apply.php';$callback_path=hrm_ess_self_change_route_callback_path($ess_apply_script,$suffix);
$secure=function_exists('session_transport_is_https')&&session_transport_is_https();$authorized=hrm_ess_self_change_review_executor_authorized();$ready=hrm_ess_self_change_route_ready_for('1.0.455');$message='';$ok_message='';
if($ess_apply_raw_method==='GET'&&isset($_GET['state'])){
    if(!$secure||!$authorized||!$ready||!hrm_ess_self_change_route_consume_attempt($now)||$company<0||$callback_path===false){http_response_code(403);exit;}$request=hrm_ess_self_change_route_parse_callback($ess_apply_raw_method,$ess_apply_raw_query);if(!is_array($request)){http_response_code(400);exit;}
    if($request['kind']==='error'){hrm_ess_self_change_route_terminalize_error($company,(string)$request['state'],(string)$request['error']);hrm_ess_self_change_reauth_forget_pending((string)$request['state']);hrm_ess_self_change_route_redirect_local($ess_apply_script,$suffix,'failed');exit;}
    $result=hrm_ess_self_change_reauth_complete_oidc($company,(string)$request['state'],(string)$request['code'],$callback_path);$status=is_array($result)?(string)($result['status']??'denied'):'denied';if($status==='assured'&&hrm_ess_self_change_route_bind_assured($result,$now)){hrm_ess_self_change_route_reset_attempts();hrm_ess_self_change_route_redirect_local($ess_apply_script,$suffix,'assured');exit;}if($status==='retry_later')hrm_ess_self_change_reauth_forget_pending((string)$request['state']);hrm_ess_self_change_route_redirect_local($ess_apply_script,$suffix,$status==='retry_later'?'retry':'failed');exit;
}
function ess_apply_id($v){return hrm_ess_self_change_review_positive_id(is_scalar($v)?(string)$v:$v);}
$action=(string)($_POST['route_action']??'');if($ess_apply_raw_method==='POST'){
    if(!$authorized||!$ready||!$secure||!check_csrf_token()||!hrm_ess_self_change_route_consume_attempt($now))$message=_('The executor action was rejected. No profile state was changed.');
    elseif(!hrm_ess_self_change_route_supported_auth_method())$message=_('This session does not support the required reauthentication method.');
    else{$request_id=ess_apply_id($_POST['request_id']??'');
        if($action==='start_execute_step_up'){$prepared=$request_id===false?false:hrm_ess_self_change_reauth_action_context('execute',$request_id,'');$token=is_array($prepared)?hrm_ess_self_change_reauth_issue_csrf($prepared,$now):false;$result=$token===false?false:hrm_ess_self_change_reauth_start_oidc($prepared,$token,$callback_path,HRM_ESS_SELF_CHANGE_REAUTH_TRANSACTION_TTL,$now);if(is_array($result)&&($result['status']??'')==='authorization_required'&&isset($result['authorization_url'])&&hrm_ess_self_change_route_redirect_provider((string)$result['authorization_url']))exit;$message=is_array($result)&&($result['status']??'')==='retry_later'?_('Independent reauthentication is temporarily unavailable. No profile state was changed.'):_('Independent reauthentication could not be started. No profile state was changed.');}
        elseif($action==='execute_request'){$prepared=$request_id===false?false:hrm_ess_self_change_reauth_action_context('execute',$request_id,'');$password=(string)($_POST['current_password']??'');$nonce=is_array($prepared)?hrm_ess_self_change_route_operation_nonce((string)$prepared['action_hash']):false;$receipt=is_array($prepared)&&$nonce!==false&&hrm_ess_self_change_reauth_local_password($password)?execute_hrm_ess_self_profile_change($request_id,$nonce):false;if($receipt===false)$message=_('Execution failed closed. No partial profile state was retained.');else{hrm_ess_self_change_route_operation_nonce((string)$prepared['action_hash'],true);hrm_ess_self_change_route_reset_attempts();$ok_message=sprintf(_('Request applied under execution receipt #%d.'),(int)$receipt);}unset($password,$nonce);}
        elseif($action==='confirm_execute'){$assured=hrm_ess_self_change_route_assured('execute',$now);$confirm=(string)($_POST['confirm_csrf']??'');$prepared=is_array($assured)?hrm_ess_self_change_reauth_action_context('execute',(int)$assured['request_id'],''):false;$valid=is_array($assured)&&is_array($prepared)&&hash_equals((string)$assured['action_hash'],(string)$prepared['action_hash'])&&hrm_ess_self_change_route_consume_confirm_csrf($assured,$confirm,$now);$nonce=$valid?hrm_ess_self_change_route_operation_nonce((string)$prepared['action_hash']):false;$receipt=$nonce===false?false:hrm_ess_self_change_route_run_governed($prepared,'',function()use($prepared,$nonce){return execute_hrm_ess_self_profile_change((int)$prepared['request_id'],$nonce);});if($receipt===false)$message=_('Reauthenticated execution failed closed. No partial profile state was retained.');else{hrm_ess_self_change_route_operation_nonce((string)$prepared['action_hash'],true);hrm_ess_self_change_route_reset_attempts();$ok_message=sprintf(_('Request applied under execution receipt #%d.'),(int)$receipt);}unset($assured,$confirm,$nonce);}
        else $message=_('The requested executor operation is not allowed.');
    }
}
page(_($help_context='Apply Profile Changes'));echo '<main class="center" style="max-width:900px;margin:0 auto;text-align:left" aria-labelledby="ess-apply-title">';if(!$authorized){display_error(_('Distinct executor authority is required.'));echo '</main>';end_page();exit;}if(!$ready){display_error(_('Software Upgrade must be completed before this executor route is available.'));echo '</main>';end_page();exit;}if(!$secure){display_error(_('This executor route requires HTTPS.'));echo '</main>';end_page();exit;}if(!hrm_ess_self_change_route_supported_auth_method()){display_error(_('This session must use local-password or approved federated OIDC authentication.'));echo '</main>';end_page();exit;}if($message!=='')display_error($message);if($ok_message!=='')display_notification($ok_message);if(($_GET['step_up']??'')==='failed')display_error(_('Independent reauthentication failed or was cancelled. No profile state was changed.'));if(($_GET['step_up']??'')==='retry')display_warning(_('Independent reauthentication must be restarted. No profile state was changed.'));
echo '<h2 id="ess-apply-title">'._('Apply Profile Changes').'</h2><p>'._('This route is executor-only. The executor must be distinct from both maker and checker. Before application, current identity binding, encrypted payload integrity and stale baseline are revalidated. Bank, tax, identifier, compensation, payroll and accounting authority are excluded.').'</p>';
$assured=hrm_ess_self_change_route_assured('execute',$now);$selected=is_array($assured)?(int)$assured['request_id']:ess_apply_id($_GET['request_id']??'');$candidates=hrm_ess_self_change_review_candidates('executor',50);if($candidates===false)display_error(_('Execution candidates could not be resolved safely.'));else{echo '<section aria-labelledby="ess-apply-queue"><h3 id="ess-apply-queue">'._('Approved execution queue').'</h3>';if(!$candidates)echo '<p>'._('No approved request is eligible for this distinct executor.').'</p>';else{echo '<ul>';foreach($candidates as $c)echo '<li><a href="?request_id='.(int)$c['request_id'].'">'.sprintf(_('Request #%d'),(int)$c['request_id']).'</a> — '.htmlspecialchars(implode(', ',$c['field_names']),ENT_QUOTES,'UTF-8').'</li>';echo '</ul>';}echo '</section>';}
if($selected!==false&&$selected>0){$detail=hrm_ess_self_change_review_detail('executor',$selected);if(!is_array($detail))display_error(_('The selected request is not available to this executor.'));else{echo '<section aria-labelledby="ess-apply-detail"><h3 id="ess-apply-detail">'.sprintf(_('Apply request #%d'),(int)$detail['request_id']).'</h3>';hrm_ess_self_change_review_render_values($detail);echo '<p aria-live="polite">'._('Application writes only the frozen bounded field set and creates an immutable execution receipt. A stale baseline or changed authorization fails closed.').'</p>';$method=hrm_ess_self_change_route_auth_method();$confirming=is_array($assured)&&(int)$assured['request_id']===(int)$detail['request_id'];start_form();hidden('_token',ensure_csrf_token());hidden('request_id',(int)$detail['request_id']);if($confirming){hidden('route_action','confirm_execute');hidden('confirm_csrf',hrm_ess_self_change_route_issue_confirm_csrf($assured,$now));submit_center('confirm_execute',_('Confirm Apply Request'));}elseif($method==='local_password'){hidden('route_action','execute_request');echo '<label for="ess-apply-password">'._('Current password:').'</label> <input id="ess-apply-password" type="password" name="current_password" maxlength="512" autocomplete="current-password" required>';submit_center('execute_request',_('Apply Approved Request'));}else{hidden('route_action','start_execute_step_up');submit_center('reauth_execute',_('Reauthenticate to Apply Request'));}end_form();echo '</section>';}}
echo '</main>';end_page();
